"""
JSON to PostgreSQL 마이그레이션 스크립트

모든 JSON 파일의 데이터를 PostgreSQL 데이터베이스로 마이그레이션합니다.
중복 제거 및 데이터 검증 기능 포함.
"""
import sys
from pathlib import Path
from typing import List, Dict, Tuple
from datetime import datetime
import argparse

# 프로젝트 루트를 sys.path에 추가
project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))

from tqdm import tqdm
from backend.data_loader import _load_from_json, remove_duplicates
from backend.db.session import get_session, init_db
from backend.db.repository import TransactionRepository
from backend.db.models import Transaction


def validate_data(items: List[Dict]) -> Tuple[List[Dict], List[Dict]]:
    """
    데이터 검증

    Args:
        items: 원본 데이터 리스트

    Returns:
        (유효한 데이터, 무효한 데이터)
    """
    valid = []
    invalid = []

    for item in items:
        # 필수 원본 필드 체크 (normalized fields는 Transaction.from_dict에서 자동 생성됨)
        # 최소한 API 타입과 거래 날짜 정보가 있어야 함
        required_fields = ['_api_type', 'dealYear', 'dealMonth', 'dealDay']
        missing_fields = [f for f in required_fields if not item.get(f)]

        if missing_fields:
            item['_validation_error'] = f"Missing fields: {missing_fields}"
            invalid.append(item)
        else:
            valid.append(item)

    return valid, invalid


def generate_migration_report(
    total_json: int,
    total_after_dedup: int,
    valid: int,
    invalid: int,
    db_stats: Dict,
    duration_seconds: float
) -> str:
    """
    마이그레이션 리포트 생성

    Returns:
        마크다운 형식의 리포트
    """
    report = f"""
# JSON to PostgreSQL 마이그레이션 리포트

**일시**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**소요 시간**: {duration_seconds:.2f}초

## 1. 데이터 로드 (JSON)

- 원본 JSON 레코드: **{total_json:,}개**
- 중복 제거 후: **{total_after_dedup:,}개** (중복 {total_json - total_after_dedup:,}개 제거)

## 2. 데이터 검증

- 유효한 레코드: **{valid:,}개** ✅
- 무효한 레코드: **{invalid:,}개** ❌

## 3. 데이터베이스 삽입 결과

- 삽입 성공: **{db_stats.get('inserted', 0):,}개**
- 업데이트: **{db_stats.get('updated', 0):,}개**
- 에러: **{db_stats.get('errors', 0):,}개**

## 4. 최종 통계

- 데이터베이스 총 레코드: **{db_stats.get('total_in_db', 0):,}개**
- 성공률: **{(db_stats.get('inserted', 0) / valid * 100 if valid > 0 else 0):.2f}%**

## 5. 검증

{'✅ 마이그레이션 성공' if db_stats.get('inserted', 0) == valid else '⚠️  일부 데이터 누락'}

---
*Generated by migrate_json_to_postgres.py*
"""
    return report


def main():
    """메인 마이그레이션 함수"""
    parser = argparse.ArgumentParser(description='JSON to PostgreSQL 마이그레이션')
    parser.add_argument('--dry-run', action='store_true', help='실제 삽입 없이 검증만 수행')
    parser.add_argument('--batch-size', type=int, default=1000, help='배치 크기 (기본값: 1000)')
    parser.add_argument('--on-conflict', choices=['ignore', 'update'], default='ignore',
                        help='중복 시 처리 (기본값: ignore)')
    args = parser.parse_args()

    print("=" * 80)
    print("JSON to PostgreSQL 마이그레이션 시작")
    print("=" * 80)

    start_time = datetime.now()

    # 1. 데이터베이스 초기화
    print("\n[1/6] 데이터베이스 초기화...")
    if not args.dry_run:
        init_db()
        print("✅ 테이블 생성 완료")
    else:
        print("ℹ️  DRY-RUN 모드: 테이블 생성 스킵")

    # 2. JSON 데이터 로드
    print("\n[2/6] JSON 파일에서 데이터 로드...")
    items, debug_info = _load_from_json(None, debug=True)
    print(f"✅ {len(items):,}개 레코드 로드 완료")
    print(f"   - 성공 파일: {len(debug_info.get('successful_files', []))}개")
    print(f"   - 실패 파일: {len(debug_info.get('failed_files', []))}개")

    if not items:
        print("❌ 로드된 데이터가 없습니다. 종료합니다.")
        return

    total_json = len(items)

    # 3. 중복 제거
    print("\n[3/6] 중복 제거...")
    items = remove_duplicates(items)
    total_after_dedup = len(items)
    print(f"✅ {total_after_dedup:,}개 유니크 레코드 (중복 {total_json - total_after_dedup:,}개 제거)")

    # 4. 데이터 검증
    print("\n[4/6] 데이터 검증...")
    valid_items, invalid_items = validate_data(items)
    print(f"✅ 유효: {len(valid_items):,}개")
    if invalid_items:
        print(f"⚠️  무효: {len(invalid_items):,}개")
        for item in invalid_items[:5]:  # 처음 5개만 출력
            print(f"   - {item.get('_validation_error', 'Unknown error')}")

    # 5. 데이터베이스 삽입
    print(f"\n[5/6] PostgreSQL 삽입 ({args.on_conflict} 모드)...")
    db_stats = {'inserted': 0, 'updated': 0, 'errors': 0}

    if not args.dry_run:
        with get_session() as session:
            repository = TransactionRepository(session)

            # 진행률 표시
            with tqdm(total=len(valid_items), desc="삽입 중", unit="레코드") as pbar:
                batch_size = args.batch_size
                for i in range(0, len(valid_items), batch_size):
                    batch = valid_items[i:i + batch_size]
                    batch_stats = repository.bulk_insert_transactions(
                        batch,
                        batch_size=batch_size,
                        on_conflict=args.on_conflict
                    )
                    db_stats['inserted'] += batch_stats['inserted']
                    db_stats['updated'] += batch_stats['updated']
                    db_stats['errors'] += batch_stats['errors']
                    pbar.update(len(batch))

        print(f"✅ 삽입 완료: {db_stats['inserted']:,}개")
        if db_stats['updated'] > 0:
            print(f"   업데이트: {db_stats['updated']:,}개")
        if db_stats['errors'] > 0:
            print(f"   에러: {db_stats['errors']:,}개")

        # 최종 DB 통계
        with get_session() as session:
            repository = TransactionRepository(session)
            final_stats = repository.get_statistics()
            db_stats['total_in_db'] = final_stats['total']
            print(f"\n📊 데이터베이스 총 레코드: {final_stats['total']:,}개")
            print(f"   API 타입별:")
            for api_type, count in final_stats['by_type'].items():
                print(f"   - {api_type}: {count:,}개")

    else:
        print("ℹ️  DRY-RUN 모드: 실제 삽입 스킵")
        db_stats['inserted'] = len(valid_items)
        db_stats['total_in_db'] = len(valid_items)

    # 6. 리포트 생성
    print("\n[6/6] 마이그레이션 리포트 생성...")
    end_time = datetime.now()
    duration = (end_time - start_time).total_seconds()

    report = generate_migration_report(
        total_json=total_json,
        total_after_dedup=total_after_dedup,
        valid=len(valid_items),
        invalid=len(invalid_items),
        db_stats=db_stats,
        duration_seconds=duration
    )

    # 리포트 저장
    report_path = Path(__file__).parent / f"migration_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    report_path.write_text(report, encoding='utf-8')
    print(f"✅ 리포트 저장: {report_path}")

    # 콘솔 출력
    print("\n" + "=" * 80)
    print(report)
    print("=" * 80)

    # 성공 여부
    if db_stats['inserted'] == len(valid_items) and db_stats['errors'] == 0:
        print("\n🎉 마이그레이션 성공!")
        return 0
    else:
        print("\n⚠️  마이그레이션 완료 (일부 에러 발생)")
        return 1


if __name__ == '__main__':
    sys.exit(main())
